In [12]:
from sklearn.datasets import fetch_openml 
import sklearn
import matplotlib.pyplot as plt
from sklearn import neighbors
import numpy as np
from sklearn import model_selection
import time
from sklearn.neural_network import MLPClassifier
from sklearn import svm
from sklearn.metrics import precision_score
import random as rd
from numpy import linspace
from sklearn.metrics import confusion_matrix
sklearn.__version__

'0.24.2'

In [2]:
mnist = fetch_openml('mnist_784')

In [3]:
#On réduit la taille du jeu de données car SVM devient très lent quand on dépasse 10000 données d'entrée
indexes = np.random.randint(70000, size=7000)
data = mnist.data.values[indexes]
target = mnist.target[indexes]


xtrain,  xtest,  ytrain,  ytest = model_selection.train_test_split(data, target, train_size = 0.7)
clf = svm.SVC(kernel="linear", verbose = True)

In [4]:
clf.fit(xtrain, ytrain)
precision_score(ytest, clf.predict(xtest), average='micro')

[LibSVM]

0.9071428571428571

In [7]:
#Precomputed ne fonctionne pas car il nécessite une forme particulière des données en entrée
noyaux = ["poly", "rbf", "sigmoid"]#, "precomputed"] 

xtrain,  xtest,  ytrain,  ytest = model_selection.train_test_split(data, target, train_size = 0.7)
for noyau in noyaux:
    start_time = time.time()
    clf = svm.SVC(kernel=noyau)
    clf.fit(xtrain, ytrain)
    predicted = precision_score(ytest, clf.predict(xtest), average='micro')
    print(f"Pour le noyau {noyau}, la précision est de {predicted} après {time.time() - start_time} secondes.")

Pour le noyau poly, la précision est de 0.9466666666666667 après 2.251969814300537 secondes.
Pour le noyau rbf, la précision est de 0.96 après 3.699800968170166 secondes.
Pour le noyau sigmoid, la précision est de 0.8509523809523809 après 2.944850206375122 secondes.


In [11]:
C = linspace(0.1, 1, 20)

for c in C:
    start_time = time.time()
    clf = svm.SVC(C=c)
    clf.fit(xtrain, ytrain)
    predicted = precision_score(ytest, clf.predict(xtest), average='micro')
    print(f"Pour C = {c}, la précision est de {predicted} après {time.time() - start_time} secondes.")
#Plus C est proche de 1, plus l'entrainement est rapide et meilleur est le résultat

Pour C = 0.1, la précision est de 0.9266666666666666 après 6.597294330596924 secondes.
Pour C = 0.1473684210526316, la précision est de 0.9338095238095238 après 5.817837715148926 secondes.
Pour C = 0.19473684210526315, la précision est de 0.9380952380952381 après 5.327130079269409 secondes.
Pour C = 0.24210526315789474, la précision est de 0.9404761904761905 après 4.8611860275268555 secondes.
Pour C = 0.2894736842105263, la précision est de 0.9452380952380952 après 4.730261564254761 secondes.
Pour C = 0.33684210526315794, la précision est de 0.9461904761904761 après 4.412717819213867 secondes.
Pour C = 0.38421052631578945, la précision est de 0.9485714285714286 après 4.461808681488037 secondes.
Pour C = 0.43157894736842106, la précision est de 0.949047619047619 après 4.1621620655059814 secondes.
Pour C = 0.4789473684210527, la précision est de 0.9514285714285714 après 4.1797730922698975 secondes.
Pour C = 0.5263157894736842, la précision est de 0.9523809523809523 après 4.13284015655517

In [14]:
cm = confusion_matrix(ytest, clf.predict(xtest))
print(cm)

[[205   0   0   0   0   2   1   0   0   1]
 [  0 255   0   2   0   0   0   0   0   1]
 [  1   1 202   0   0   2   2   0   2   0]
 [  0   1   6 192   0   3   1   2   5   1]
 [  0   0   0   0 194   0   2   0   0   5]
 [  0   0   0   6   1 169   1   0   2   2]
 [  0   0   0   0   0   2 190   0   0   0]
 [  0   0   2   0   0   0   0 226   0   6]
 [  1   3   0   4   2   5   2   0 177   1]
 [  0   0   0   1   2   0   0   0   0 206]]
